from pylab import *

a=loadtxt("pur_conexiones8.dat")
b=loadtxt("pur_conexiones9.dat")
c=loadtxt("pur_conexiones10.dat")
d=loadtxt("pur_conexiones11.dat")
e=loadtxt("pur_conexiones12.dat")
f=loadtxt("pur_conexiones13.dat")
g=loadtxt("pur_conexiones7.dat")
h=loadtxt("pur_conexiones.dat")
i=loadtxt("pur_conexiones2.dat")
j=loadtxt("pur_conexiones3.dat")
k=loadtxt("pur_conexiones4.dat")
l=loadtxt("pur_conexiones5.dat")

plot(a,label="12")
plot(b,label="11")
plot(c,label="10")
plot(d,label="9")
plot(e,label="8")
plot(f,label="7")
plot(g,label="6")
plot(h,label="5")
plot(i,label="4")
plot(j,label="3")
plot(k,label="2")
plot(l,label="1")

legend()
xlabel("$t$")
ylabel("$P$")
show()